### ISSUE TITLE
0.1.2 is a breaking release

### ISSUE THREAD

**Issue by bcherny** [ajbogh/flatten-glob#3]
We are using flatten-glob to match something like this:

``` js
flatGlob([
  'app/**/*.js',
  '!app/**/*.spec.js'
])
```

With 0.1.1 this worked fine (matching *.js files but excluding *.spec.js files).
With 0.1.2 this fails to exclude *.spec.js files.

cc @kgrubb

**Comment by kgrubb** [comment]
Ah, I'm certain this is due to the glob version change from 3-7. I found this in the glob documentation:

> Previously, this module let you mark a pattern as a "negated" pattern if it started with a ! character. These options were deprecated in version 5, and removed in version 6.To specify things that should not match, use the ignore option.

@ajbogh, reverting glob to the previously pinned version will return behavior back to how it was, making this release non-breaking. However, the previous version being used was subject to a RegExp DoS issue in minimatch, so I'm unsure what the best solution should be here.

**Comment by ajbogh** [comment]
Thanks! I'll revert and research a new solution.

**Comment by bcherny** [comment]
Another option could be to release this as 1.0.0 instead.

**Comment by ajbogh** [comment]
This is fixed in v0.1.3, please feel free to upgrade. I will consider bumping the major version if this release sits well. 

The change I made was to the removeEntries function, which scans through the glob patterns for entries starting with "!". The new code uses the substring of the glob pattern starting at position 1, ignoring the ! symbol to get all matching files. Any file that matches will be removed from the final array, just as before. The new code works with glob 7.0.5 as well.

The change is in commit https://github.com/ajbogh/flatten-glob/commit/534e4fbf23438776423ca2cded77a679d0b8bcdd.
